services:
  alone-bot:
    build: .
    container_name: alone-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./config.toml:/app/config.toml:ro
    labels:
      - homepage.group=Services
      - homepage.name=Alone Bot
      - homepage.icon=mdi-robot-happy
      - homepage.description=Telegram Bot Activity Suggester
